<?php

namespace Culture\JuridiqueBundle\Repository;

/**
 * CahierChargeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CahierChargeRepository extends \Doctrine\ORM\EntityRepository
{
}
