<?php

namespace Culture\JuridiqueBundle\Repository;

/**
 * PhaseProjetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhaseProjetRepository extends \Doctrine\ORM\EntityRepository
{
}
