<?php

namespace Culture\JuridiqueBundle\Repository;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
     /**
     * Returns all posts
     *
     * @return array
     */
    public function findAll()
    {
       
        
        $qb = $this->createQueryBuilder('post');
   
        return $qb->getQuery('ar')
            ->setHint(Query::HINT_CUSTOM_OUTPUT_WALKER, 'Gedmo\\Translatable\\Query\\TreeWalker\\TranslationWalker')
            ->getResult();
    }
}
