<?php

namespace Culture\JuridiqueBundle\Repository;

/**
 * ProjetLoiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjetLoiRepository extends \Doctrine\ORM\EntityRepository
{
     public function findOrdrebByDate() {

        $query = $this->createQueryBuilder('a');
        $query->orderBy('a.date', 'DESC');
       
        return $query->getQuery()->getResult();
    }
}
