<?php

namespace Culture\JuridiqueBundle\Repository;

/**
 * SousCategorie2Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SousCategorie2Repository extends \Doctrine\ORM\EntityRepository
{
}
