<?php

namespace Culture\JuridiqueBundle\Repository;

/**
 * SousCategorie1Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SousCategorie1Repository extends \Doctrine\ORM\EntityRepository
{
}
