<?php

namespace Culture\JuridiqueBundle\Repository;

/**
 * StatutTexteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatutTexteRepository extends \Doctrine\ORM\EntityRepository
{
}
