<?php

namespace Culture\JuridiqueBundle\Repository;

/**
 * TypeTexteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeTexteRepository extends \Doctrine\ORM\EntityRepository
{
}
