services:
    economat.main.twig.translate_extension:
        class: Culture\JuridiqueBundle\Twig\TranslateExtension
        arguments: ["@request_stack"]
        tags:
            - { name : twig.extension }