# app/config/security.yml
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                login_path: /login
                check_path: /login_check
                always_use_default_target_path: false
                default_target_path: culture_back


            logout:       true
            anonymous:    true
            remember_me:
                key:      '%secret%'
                lifetime: 3600
                path:     /
                domain:   ~ # Defaults to the current domain from $_SERVER
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/%locale%/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/%locale%/admin, role: ROLE_USER }
        - { path: ^/%locale%/admin/, role: ROLE_USER }
