constitution_index:
    path:     /
    defaults: { _controller: "CultureJuridiqueBundle:Constitution:index" }
    methods:  GET

constitution_show:
    path:     /{id}/show
    defaults: { _controller: "CultureJuridiqueBundle:Constitution:show" }
    methods:  GET

constitution_new:
    path:     /new
    defaults: { _controller: "CultureJuridiqueBundle:Constitution:new" }
    methods:  [GET, POST]

constitution_edit:
    path:     /{id}/edit
    defaults: { _controller: "CultureJuridiqueBundle:Constitution:edit" }
    methods:  [GET, POST]

constitution_delete:
    path:     /{id}/delete
    defaults: { _controller: "CultureJuridiqueBundle:Constitution:delete" }
    methods:  [GET, POST]
