phaseprojet_index:
    path:     /
    defaults: { _controller: "CultureJuridiqueBundle:PhaseProjet:index" }
    methods:  GET

phaseprojet_show:
    path:     /{id}/show
    defaults: { _controller: "CultureJuridiqueBundle:PhaseProjet:show" }
    methods:  GET

phaseprojet_new:
    path:     /new
    defaults: { _controller: "CultureJuridiqueBundle:PhaseProjet:new" }
    methods:  [GET, POST]

phaseprojet_edit:
    path:     /{id}/edit
    defaults: { _controller: "CultureJuridiqueBundle:PhaseProjet:edit" }
    methods:  [GET, POST]

phaseprojet_delete:
    path:     /{id}/delete
    defaults: { _controller: "CultureJuridiqueBundle:PhaseProjet:delete" }
    methods:  [GET, POST]
