projetloi_index:
    path:     /
    defaults: { _controller: "CultureJuridiqueBundle:ProjetLoi:index" }
    methods:  GET

projetloi_show:
    path:     /{id}/show
    defaults: { _controller: "CultureJuridiqueBundle:ProjetLoi:show" }
    methods:  GET

projetloi_new:
    path:     /new
    defaults: { _controller: "CultureJuridiqueBundle:ProjetLoi:new" }
    methods:  [GET, POST]

projetloi_edit:
    path:     /{id}/edit
    defaults: { _controller: "CultureJuridiqueBundle:ProjetLoi:edit" }
    methods:  [GET, POST]

projetloi_delete:
    path:     /{id}/delete
    defaults: { _controller: "CultureJuridiqueBundle:ProjetLoi:delete" }
    methods:  [GET, POST]
