service_index:
    path:     /
    defaults: { _controller: "CultureJuridiqueBundle:service:index" }
    methods:  GET

service_show:
    path:     /{id}/show
    defaults: { _controller: "CultureJuridiqueBundle:service:show" }
    methods:  GET

service_new:
    path:     /new
    defaults: { _controller: "CultureJuridiqueBundle:service:new" }
    methods:  [GET, POST]

service_edit:
    path:     /{id}/edit
    defaults: { _controller: "CultureJuridiqueBundle:service:edit" }
    methods:  [GET, POST]

service_delete:
    path:     /{id}/delete
    defaults: { _controller: "CultureJuridiqueBundle:service:delete" }
    methods:  [GET, POST]
