souscategorie1_index:
    path:     /
    defaults: { _controller: "CultureJuridiqueBundle:SousCategorie1:index" }
    methods:  GET

souscategorie1_show:
    path:     /{id}/show
    defaults: { _controller: "CultureJuridiqueBundle:SousCategorie1:show" }
    methods:  GET

souscategorie1_new:
    path:     /new
    defaults: { _controller: "CultureJuridiqueBundle:SousCategorie1:new" }
    methods:  [GET, POST]

souscategorie1_edit:
    path:     /{id}/edit
    defaults: { _controller: "CultureJuridiqueBundle:SousCategorie1:edit" }
    methods:  [GET, POST]

souscategorie1_delete:
    path:     /{id}/delete
    defaults: { _controller: "CultureJuridiqueBundle:SousCategorie1:delete" }
    methods:  [GET, POST]
