typetexte_index:
    path:     /
    defaults: { _controller: "CultureJuridiqueBundle:TypeTexte:index" }
    methods:  GET

typetexte_show:
    path:     /{id}/show
    defaults: { _controller: "CultureJuridiqueBundle:TypeTexte:show" }
    methods:  GET

typetexte_new:
    path:     /new
    defaults: { _controller: "CultureJuridiqueBundle:TypeTexte:new" }
    methods:  [GET, POST]

typetexte_edit:
    path:     /{id}/edit
    defaults: { _controller: "CultureJuridiqueBundle:TypeTexte:edit" }
    methods:  [GET, POST]

typetexte_delete:
    path:     /{id}/delete
    defaults: { _controller: "CultureJuridiqueBundle:TypeTexte:delete" }
    methods:  [GET, POST]
